esphome:
  name: iwr6843-radar
  platform: ESP32
  board: esp32dev

# Enable logging (disable hardware UART logging!)
logger:
  level: DEBUG
  baud_rate: 0  # IMPORTANT: Disable hardware UART0 logging

# Enable Home Assistant API
api:

ota:

wifi:
  ssid: "Your_SSID"
  password: "Your_Password"

# ═══════════════════════════════════════════════════════════════════════════
# UART Configuration - Single-UART Mode @ 115200 baud
# ═══════════════════════════════════════════════════════════════════════════
# Both CLI commands and radar data use the same UART @ 115200 baud
# This is the RECOMMENDED configuration for simplicity and reliability
# ═══════════════════════════════════════════════════════════════════════════

uart:
  - id: uart_radar
    tx_pin: GPIO27      # ESP32 TX → IWR6843 UART0_RX
    rx_pin: GPIO26      # ESP32 RX ← IWR6843 UART0_TX
    baud_rate: 115200   # Single baudrate for CLI + Data

# ═══════════════════════════════════════════════════════════════════════════
# IWR6843 Radar Component - Single-UART Mode
# ═══════════════════════════════════════════════════════════════════════════

external_components:
  - source: github://bytelink-ai/IWR6843@main
    components: [ iwr6843 ]
    refresh: 1min

iwr6843:
  id: my_radar
  config_uart_id: uart_radar   # CLI Port
  data_uart_id: uart_radar     # Data Port (SAME as config!)
  sop2_pin: GPIO33             # Optional: Boot mode select
  nrst_pin: GPIO32             # Optional: Reset pin
  ceiling_height: 290          # cm
  max_tracks: 5
  update_interval: 50ms

# ═══════════════════════════════════════════════════════════════════════════
# Binary Sensor - Presence Detection
# ═══════════════════════════════════════════════════════════════════════════

binary_sensor:
  - platform: iwr6843
    iwr6843_id: my_radar
    presence:
      name: "Radar Presence"
      device_class: presence

# ═══════════════════════════════════════════════════════════════════════════
# Sensors
# ═══════════════════════════════════════════════════════════════════════════

sensor:
  - platform: iwr6843
    iwr6843_id: my_radar
    num_targets:
      name: "Number of Targets"
    frame_number:
      name: "Frame Number"

# ═══════════════════════════════════════════════════════════════════════════
# HARDWARE WIRING
# ═══════════════════════════════════════════════════════════════════════════
#   ESP32 GPIO27  →  IWR6843 UART0_RX (PINN4/PADBD)
#   ESP32 GPIO26  ←  IWR6843 UART0_TX (PINN5/PADBE)
#   ESP32 GPIO33  →  IWR6843 SOP2 (optional)
#   ESP32 GPIO32  →  IWR6843 NRST (optional)
#   ESP32 GND     ⇄  IWR6843 GND
#
# FIRMWARE: xwr68xx_overhead_uart0_115200.bin
# ═══════════════════════════════════════════════════════════════════════════
