name: Bug Report
description: Report a bug with the IWR6843 component
title: "[Bug]: "
labels: ["bug", "triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Describe the bug
      placeholder: Tell us what went wrong
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: What should have happened
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce the issue?
      placeholder: |
        1. Configure component with...
        2. Flash ESP32
        3. See error
    validations:
      required: true

  - type: input
    id: esphome-version
    attributes:
      label: ESPHome Version
      description: What version of ESPHome are you using?
      placeholder: "2024.2.0"
    validations:
      required: true

  - type: input
    id: firmware-version
    attributes:
      label: IWR6843 Firmware Version
      description: Which firmware version is on your IWR6843?
      placeholder: "v1.0.0 SPI"
    validations:
      required: true

  - type: dropdown
    id: esp-board
    attributes:
      label: ESP32 Board
      description: Which ESP32 board are you using?
      options:
        - ESP32-DevKit
        - ESP32-WROOM-32
        - ESP32-S2
        - ESP32-S3
        - ESP32-C3
        - Other
    validations:
      required: true

  - type: textarea
    id: config
    attributes:
      label: YAML Configuration
      description: Paste your ESPHome YAML configuration
      render: yaml
      placeholder: |
        iwr6843:
          id: my_radar
          ...
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: Paste relevant log output
      render: text
      placeholder: |
        [E][iwr6843] Error message here...
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Troubleshooting Checklist
      description: Have you tried these steps?
      options:
        - label: I have read the documentation
          required: true
        - label: I have checked existing issues
          required: true
        - label: CS pin has 10kÎ© pull-up resistor
          required: false
        - label: IWR6843 firmware is correct SPI version
          required: false
        - label: All pin connections are verified
          required: false

