name: Feature Request
description: Suggest a new feature for the IWR6843 component
title: "[Feature]: "
labels: ["enhancement"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature!

  - type: textarea
    id: problem
    attributes:
      label: Is your feature request related to a problem?
      description: Describe the problem you're trying to solve
      placeholder: I'm frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: What would you like to see implemented?
      placeholder: I would like to...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: Have you thought of other solutions?
      placeholder: Alternative solutions...
    validations:
      required: false

  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Add any other context or screenshots
      placeholder: Additional information...
    validations:
      required: false

  - type: dropdown
    id: contribution
    attributes:
      label: Would you like to contribute this feature?
      description: Are you willing to submit a pull request?
      options:
        - "Yes, I can implement this"
        - "No, I need help with implementation"
        - "Not sure"
    validations:
      required: false

